# Generated by Django 5.0.4 on 2024-05-11 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0001_initial'),
        ('set', '0003_executed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='set.set'),
        ),
    ]
