# Generated by Django 5.0.4 on 2024-05-11 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0002_alter_case_set'),
        ('type', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='type.type'),
        ),
    ]
