# Generated by Django 5.0.4 on 2024-05-11 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0003_alter_case_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executed',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case.case'),
        ),
    ]
