# Generated by Django 5.0.4 on 2024-05-03 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('set', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='set',
            old_name='summery',
            new_name='summary',
        ),
    ]
