# Generated by Django 5.0.4 on 2024-05-02 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.IntegerField(default=0),
        ),
    ]
