# Generated by Django 5.0.4 on 2024-05-02 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_project_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_by',
            field=models.IntegerField(default=0),
        ),
    ]
